### ISSUE TITLE
Doesn't appear to work with gulp.watch

### ISSUE THREAD

**Issue by ericgrosse** [teambition/gulp-sequence#10]
I have a watch task that includes the following:

```
gulp.watch('./app/**/*.js', ['lint', 'test']);
```

When I change it to:

```
gulp.watch('./app/**/*.js', gulpSequence('lint', 'test'));
```

The `lint` and `test` tasks don't appear to run at all on file changes.

**Comment by zensh** [comment]
`gulp.watch('./app/**/*.js', function () { return gulpSequence('lint', 'test') });`

**Comment by ericgrosse** [comment]
Given you can use `gulpSequence` in `gulp.task` without the callback function, it would be pretty cool to be able to do the same with `gulp.watch` for consistency's sake.

Call it a feature request maybe :P

Edit: Looking at your `index.js` file, I think I could do a pull request if that's of any help.

**Comment by zensh** [comment]
@ericgrosse the function that returned by gulpSequence can only run once!

**Comment by ericgrosse** [comment]
Ok. Guess I would recommend you add the proper way to use `gulpSequence` in `gulp.watch` to the readme.

**Comment by zensh** [comment]
@ericgrosse Readme updated, thank you.

``` js
gulp.watch('src/**/*.js', function (event) {
  gulpSequence('a', 'b')(function (err) {
    if (err) console.log(err)
  })
})
```

**Comment by vagusX** [comment]
nice solution
