### ISSUE TITLE
npm install  出现了问题

### ISSUE THREAD

**Issue by juntingl** [teambition/gulp-sequence#13]
![image](https://user-images.githubusercontent.com/13826695/40582010-cfc61c9e-619a-11e8-899c-75abb0e3c672.png)

**Comment by zensh** [comment]
我随便找了个项目试了下 `npm i --save-dev gulp-sequence` 正常啊

**Comment by juntingl** [comment]
@zensh 是正常的，切回官方源就好了，当我切到 淘宝源的时候就会出现这样的问题。
