### ISSUE TITLE
Changes in 0.4.2 break some tasks

### ISSUE THREAD

**Issue by tandrewnichols** [teambition/gulp-sequence#5]
With this gulpfile.js:

```
var gulp = require('gulp');
var sequence = require('gulp-sequence');
require('file-manifest').generate('./gulp', ['*.js', '!config.js']);
gulp.task('travis', sequence(['lint', 'cover', 'phantom'], 'codeclimate'));
gulp.task('test', ['cover', 'browser']);
gulp.task('default', ['lint', 'test']);
gulp.task('build', sequence('clean:dist', ['copy', 'uglify']));
```

in 0.4.1, `gulp build` produces this:

<img width="568" alt="screen shot 2015-12-18 at 11 09 10 pm" src="https://cloud.githubusercontent.com/assets/2755760/11911234/8b04f250-a5dc-11e5-98b6-9023fb3370a2.png">

In 0.4.2, it produces this:

<img width="1068" alt="screen shot 2015-12-18 at 11 08 03 pm" src="https://cloud.githubusercontent.com/assets/2755760/11911237/96fb58e2-a5dc-11e5-87ae-67825bc507e7.png">

For what it's worth, some tasks _do_ work. Running `clean:dist` directly works in both.

**Comment by zensh** [comment]
I have released v0.4.3. Please try it

**Comment by zensh** [comment]
But, do you have defined `clean:dist` task?

**Comment by tandrewnichols** [comment]
Well, yeah, like I said, it works under 0.4.1.

**Comment by tandrewnichols** [comment]
0.4.3 works also.
