### ISSUE TITLE
Differences between this and run-sequence

### ISSUE THREAD

**Issue by jonscottclark** [teambition/gulp-sequence#7]
I saw this being used in https://github.com/vigetlabs/gulp-starter and was wondering what differences there are between this repo and https://github.com/OverZealous/run-sequence ? Looks like you both released them at roughly the same time. Thanks for your input :)

**Comment by zensh** [comment]
Hi, gulp-sequence is inspired by run-sequence. When I need to run sequence tasks in gulp, I found run-sequence, but it did not meet all my needs, and I thought other perfect way to implement it with [thunks](https://github.com/thunks/thunks), so I created gulp-sequence. However, gulp-sequence was similar to run- sequence when implemented, it was limited by gulp.

You can use gulp-sequence as run-sequence simply, there is big defference:

```
gulp.task('someTask', gulpSequence(['a', 'b'], 'c', ['d', 'e'], 'f'));
```

Define a series of tasks with gulp-sequence! run-sequence can not do it.

**Comment by jonscottclark** [comment]
Thanks :)

**Comment by pcodedviral** [comment]
but it will not work in gulp4.0.0
it work in gulp3.9.1
